### ISSUE TITLE
Documentation errors: Better api help and tutorials needed

### ISSUE THREAD

**Issue by BenjaminNitschke** [dashevo/DashJS#16]
The current documentation is a great start and the getting started guides are superb and easy. However a major roadblock for any developer starting with Dash Platform is when the examples don't work or they get stuck at some point or find no api documentation.

Here are some small annoyances (plus some people in #evo-net had also trouble getting up to speed with the tutorials, maybe good feedback to recheck the initial guidelines):
- Make a payment code (both on https://github.com/dashevo/DashJS and https://dashevo.github.io/DashJS/#/getting-started/quickstart ) is producing an error: `activeAccount
  .createTransaction({
    recipient:{address:'yLptqWxjgTxtwKJuLHoGY222NnoeqYuN8h', amount:0.12}
  })
  .then((tx)=> console.log(tx));`
results in: `(node:30100) UnhandledPromiseRejectionWarning: Error: An amount in dash or in satoshis is expected to create a transaction
    at Account.createTransaction (..\dashevo\node_modules\@dashevo\wallet-lib\src\types\Account\methods\createTransaction.js:41:13)`
This works fine:
`activeAccount
  .createTransaction({
    recipient: "yLptqWxjgTxtwKJuLHoGY222NnoeqYuN8h",
    satoshis: 12000000
  })
  .then((tx)=> console.log(tx));`
- The Read a document on the same page works fine, but the code presented at https://github.com/dashevo/DashJS doesn't work:
`const profile = await sdk.platform.fetchDocuments('profile',{name:'Bob'})`

Minor improvements:
- The quickstart does not point out where the schema.json comes from, just copying/linking the example schema of the dashjs library would be helpful: https://dashevo.github.io/DashJS/#/getting-started/quickstart
- The tutorials at https://dashplatform.readme.io/docs/tutorial-connecting-to-evonet or https://dashplatform.readme.io/docs/tutorial-create-and-fund-a-wallet should be one code snippet to make it easy to copy and try out and to make clear the code belongs together
- In general a start to finish tutorial from getting the sdk ready, checking your wallet + balance, then creating an identity and registering a platform name with it would be great. currently any developer can figure it out, but instead of taking a few minutes it might take 10-30 minutes and we all know how short attention spans are these days ^^

I know I am getting more and more stuck the deeper I look as the tutorials stop abruptly and finding information in the source code is far from easy (its javascript after all ..). Good examples of detailed API documentation, having something like this for the most important few methods in each area (payment, contracts, etc.) would help a lot, especially if it is all on one easily searchable page. A lot of this information is already available at some pages at https://dashplatform.readme.io/docs or https://dashevo.github.io/DashJS/, but a lot more is needed to help new developers get up to speed and to know which methods exists and which parameters can be used:
- https://bittrex.github.io/api/v1-1
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by dalibran** [comment]
thanks for putting this together @BenjaminNitschke! we are going to discuss this during our next documentation team planning, which typically occurs on Tuesdays. someone will respond again to this letting you know about the status of these proposed improvements.

**Comment by Alex-Werner** [comment]
Hey Benjamin ! 

 Thanks a lot for the feedback.  
Points well taken (sorry for that by the way), and I do agree with you, these are actually mistakes introduced by recent breaking change and a copy/paste from the wallet-lib that is not clear. We did plan (actually is my task today) to update the documentation. 
For those you mentioned, because they are already spotted, it will be fixed in the coming PR that should be merged in the next 24hours.  

Though, I will take the effort to do a recheck, add link to the dash platform documentation when able(which wasn’t live yet), or add more useful things trying to improve the documentation (which might come later on that last part, may be post dashpay contract delivery); It’s still possible that people will get stuck, have issue with dependencies, bugs etc… and we hope to have more of this reports to help us guiding us on what is the most urgent for them, or to point mistakes (therefore, thanks again!)  
To put some context, the current state, is a quick MVP allowed by the release of Evonet, we put the effort mostly (because MVP) on providing the features for the first group of heavy enthousiasts, which is why some learners in Discord were really lost.  Now that we have a working full-stack, we consolidate around, and this will come with obviously a more stable API (were methods doesn’t just stop working because not updated in the doc) and more clear documentation.

**Comment by Alex-Werner** [comment]
The doc is now updated here : https://dashevo.github.io/DashJS/#/ 
Thank you again for the feedback, we tried to apply as much of them on it.
